services:
  - type: web
    name: schedule-viewer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: cron
    name: update-schedule
    env: python
    schedule: "0 6 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python update_schedule.py
