name: Update schedule

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download schedule
        env:
          BARNIM_USER: schule
          BARNIM_PASS: ${{ secrets.BARNIM_PASS }}
        run: |
          curl -L -u "$BARNIM_USER:$BARNIM_PASS" \
            "https://www.barnim-gymnasium.de/fileadmin/schulen/barnim-gymnasium/Dokumente/Pl%C3%A4ne/splan.pdf" \
            -o splan.pdf
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add splan.pdf
          git commit -m "Update schedule" || echo "No changes" 
          git push
