name: Update schedule

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install qpdf
        run: sudo apt-get update && sudo apt-get install -y qpdf
      - name: Download schedule
        run: |
          wget -O splan.pdf \
            "https://www.barnim-gymnasium.de/fileadmin/schulen/barnim-gymnasium/Dokumente/Pl%C3%A4ne/splan.pdf"
      - name: Decrypt PDF
        run: |
          qpdf --password=schule --decrypt splan.pdf decrypted.pdf
          mv decrypted.pdf splan.pdf
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add splan.pdf
          git commit -m "Update schedule" || echo "No changes" 
          git push
